// import TrainBooking from "../miniComponent/TrainBooking";
import { TourPackageComponent } from "../miniComponent/Tourpackage";

export const tourPackages = [
  {
    id: 1,
    imgSrc: "/public/assets/img/tours/tour-1-1.jpg",
    reviewStars: 4,
    title: "Peek Mountain View",
    days: 4,
    people: 3,
    price: 399,
    bookingLink: "tour-booking.html",
    destination: "Las Vegas, Nevada",
    departure: "3166 Providence Lane, Mira Loma, CA",
    departureTime: "Approximately 8.00AM",
    ageRestriction: "Must be 13+",
    dressCode: "Casual, light And comfortable",
    serviceIncluded: [
      "5 Star Accommodation",
      "Airport Transfer",
      "Breakfast",
      "Personal Guide",
    ],
    serviceNotIncluded: ["Gallery Ticket", "Lunch"],
    returnTime: "Approximately 7.00AM",
  },
  {
    id: 2,
    imgSrc: "/public/assets/img/tours/tour-1-2.jpg",
    reviewStars: 5,
    title: "Explore Our World",
    location: "Las Vegas, Nevada",
    days: 4,
    people: 3,
    price: 259,
    bookingLink: "tour-booking.html",
    destination: "Las Vegas, Nevada",
    departure: "3166 Providence Lane, Mira Loma, CA",
    departureTime: "Approximately 8.00AM",
    ageRestriction: "Must be 13+",
    dressCode: "Casual, light And comfortable",
    serviceIncluded: [
      "5 Star Accommodation",
      "Airport Transfer",
      "Breakfast",
      "Personal Guide",
    ],
    serviceNotIncluded: ["Gallery Ticket", "Lunch"],
    returnTime: "Approximately 7.00AM",
  },
  {
    id: 3,
    imgSrc: "/public/assets/img/tours/tour-1-3.jpg",
    reviewStars: 4,
    title: "Guided Adventures",
    location: "Las Vegas, Nevada",
    days: 4,
    people: 3,
    price: 299,
    bookingLink: "tour-booking.html",
    destination: "Las Vegas, Nevada",
    departure: "3166 Providence Lane, Mira Loma, CA",
    departureTime: "Approximately 8.00AM",
    ageRestriction: "Must be 13+",
    dressCode: "Casual, light And comfortable",
    serviceIncluded: [
      "5 Star Accommodation",
      "Airport Transfer",
      "Breakfast",
      "Personal Guide",
    ],
    serviceNotIncluded: ["Gallery Ticket", "Lunch"],
    returnTime: "Approximately 7.00AM",
  },
  {
    id: 4,
    imgSrc: "/public/assets/img/tours/tour-1-4.jpg",
    reviewStars: 3,
    title: "Relax With Beach View",
    location: "Las Vegas, Nevada",
    days: 4,
    people: 3,
    price: 299,
    bookingLink: "tour-booking.html",
    destination: "Las Vegas, Nevada",
    departure: "3166 Providence Lane, Mira Loma, CA",
    departureTime: "Approximately 8.00AM",
    ageRestriction: "Must be 13+",
    dressCode: "Casual, light And comfortable",
    serviceIncluded: [
      "5 Star Accommodation",
      "Airport Transfer",
      "Breakfast",
      "Personal Guide",
    ],
    serviceNotIncluded: ["Gallery Ticket", "Lunch"],
    returnTime: "Approximately 7.00AM",
  },
  {
    id: 5,
    imgSrc: "/public/assets/img/tours/tour-1-5.jpg",
    reviewStars: 4,
    title: "Wanderlust Wonderland",
    location: "Las Vegas, Nevada",
    days: 2,
    people: 2,
    price: 199,
    bookingLink: "tour-booking.html",
    destination: "Las Vegas, Nevada",
    departure: "3166 Providence Lane, Mira Loma, CA",
    departureTime: "Approximately 8.00AM",
    ageRestriction: "Must be 13+",
    dressCode: "Casual, light And comfortable",
    serviceIncluded: [
      "5 Star Accommodation",
      "Airport Transfer",
      "Breakfast",
      "Personal Guide",
    ],
    serviceNotIncluded: ["Gallery Ticket", "Lunch"],
    returnTime: "Approximately 7.00AM",
  },
  {
    id: 6,
    imgSrc: "/public/assets/img/tours/tour-1-6.jpg",
    reviewStars: 5,
    title: "Explore Our World",
    location: "Las Vegas, Nevada",
    days: 4,
    people: 3,
    price: 259,
    bookingLink: "tour-booking.html",
    destination: "Las Vegas, Nevada",
    departure: "3166 Providence Lane, Mira Loma, CA",
    departureTime: "Approximately 8.00AM",
    ageRestriction: "Must be 13+",
    dressCode: "Casual, light And comfortable",
    serviceIncluded: [
      "5 Star Accommodation",
      "Airport Transfer",
      "Breakfast",
      "Personal Guide",
    ],
    serviceNotIncluded: ["Gallery Ticket", "Lunch"],
    returnTime: "Approximately 7.00AM",
  },
];
const HeroSection = () => {
  return (
    <>
      <TourPackageComponent tourPackages={tourPackages} />
    </>
  );
};

export default HeroSection;
